[versions]
agp = "8.13.0"
firebaseBom = "34.4.0"
generativeai = "0.9.0"
guava = "33.3.1-android"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
lottie = "6.6.10"
material = "1.13.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
firebaseAuth = "24.0.1"
firebaseFirestore = "26.0.2"
firebaseDatabase = "22.0.1"
firebaseCrashlyticsBuildtools = "3.0.6"
reactiveStreams = "1.0.4"

[libraries]
firebase-ai = { module = "com.google.firebase:firebase-ai" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
generativeai = { module = "com.google.ai.client.generativeai:generativeai", version.ref = "generativeai" }
google-firebase-auth = { module = "com.google.firebase:firebase-auth" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebaseAuth" }
firebase-firestore = { group = "com.google.firebase", name = "firebase-firestore", version.ref = "firebaseFirestore" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }
firebase-crashlytics-buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
reactive-streams = { module = "org.reactivestreams:reactive-streams", version.ref = "reactiveStreams" }
x4-x-x = { module = "com.google.firebase:34.4.0" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

